#!/bin/bash
# Visit http://www.timeapi.org to find the correct url for your timezone. Then replace the url in the first line

#time=$(wget http://www.timeapi.org/cdt/now -q -O -)
time=$(curl -s --head http://google.com | grep ^Date: | sed 's/Date: //g')
#time=$(wget http://www.timeapi.org/cdt/now?format=%25d%20%25b%20%25Y%20%25I:%25M:%25S -q -O -)
echo "Time set!" | toilet -f mono12 -F metal
sudo date -s "`echo $time`"


